[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_AUTH0_CLIENT_ID,PUBLIC_AUTH0_DOMAIN"
  SECRETS_SCAN_ENABLED = "false"
