export enum EnvironmentVariable {
  AZURE_CLIENT_CERT = 'AZURE_CLIENT_CERT',
  AZURE_CLIENT_ID = 'AZURE_CLIENT_ID',
  AZURE_CLIENT_SECRET = 'AZURE_CLIENT_SECRET',
  AZURE_TENANT_ID = 'AZURE_TENANT_ID',

  SHAREPOINT_HOST_NAME = 'SHAREPOINT_HOST_NAME',
  SHAREPOINT_SITE_ID = 'SHAREPOINT_SITE_ID',
  SHAREPOINT_SITE_NAME = 'SHAREPOINT_SITE_NAME',

  SHAREPOINT_LEITENDE_LIST_ID = 'SHAREPOINT_LEITENDE_LIST_ID',
  SHAREPOINT_GRUPPENSTUNDEN_LIST_ID = 'SHAREPOINT_GRUPPENSTUNDEN_LIST_ID',
  SHAREPOINT_CALENDAR_LIST_ID = 'SHAREPOINT_CALENDAR_LIST_ID',
  SHAREPOINT_BLOG_LIST_ID = 'SHAREPOINT_BLOG_LIST_ID',
  SHAREPOINT_QA_LIST_ID = 'SHAREPOINT_QA_LIST_ID',
  SHAREPOINT_DOWNLOAD_FILES_DRIVE_ID = 'SHAREPOINT_DOWNLOAD_FILES_DRIVE_ID',
  SHAREPOINT_NIKOLAUS_LIST_ID = 'SHAREPOINT_NIKOLAUS_LIST_ID',
  SHAREPOINT_NIKOLAUS_DISPO_LIST_ID = 'SHAREPOINT_NIKOLAUS_DISPO_LIST_ID',
  SHAREPOINT_NIKOLAUS_HELFENDE_LIST_ID = 'SHAREPOINT_NIKOLAUS_HELFENDE_LIST_ID',
  SHAREPOINT_NIKOLAUS_EINTEILUNG_LIST_ID = 'SHAREPOINT_NIKOLAUS_EINTEILUNG_LIST_ID',

  NIKOLAUS_MAIL_SENDER = 'NIKOLAUS_MAIL_SENDER',
  NIKOLAUS_SITE_URL = 'NIKOLAUS_SITE_URL',
  OPENROUTESERVICE_API_KEY = 'OPENROUTESERVICE_API_KEY',

  SHAREPOINT_SAMMELBESTELLUNGEN_LIST_ID = 'SHAREPOINT_SAMMELBESTELLUNGEN_LIST_ID',
  SHAREPOINT_SAMMELBESTELLUNGEN_ORDERS_LIST_ID = 'SHAREPOINT_SAMMELBESTELLUNGEN_ORDERS_LIST_ID',
  SAMMELBESTELLUNG_LINK_SECRET = 'SAMMELBESTELLUNG_LINK_SECRET',
  SAMMELBESTELLUNG_MAIL_SENDER = 'SAMMELBESTELLUNG_MAIL_SENDER',
  SITE_URL = 'SITE_URL',

  CAMPFLOW_API_TOKEN = 'CAMPFLOW_API_TOKEN',
  SAMMELBESTELLUNG_CAMPFLOW_CREATE_ENABLED = 'SAMMELBESTELLUNG_CAMPFLOW_CREATE_ENABLED',

  INSTAGRAM_ACCESS_TOKEN = 'INSTAGRAM_ACCESS_TOKEN',
  SHAREPOINT_INSTAGRAM_TOKEN_LIST_ID = 'SHAREPOINT_INSTAGRAM_TOKEN_LIST_ID',
}

export function getEnvironment(variable: EnvironmentVariable): string {
  const value = process.env[variable];
  if (!value) {
    throw new Error(`Missing environment variable: ${variable}`);
  }
  return value;
}
